### PR TITLE
Remove MtGox

### PR DESCRIPTION
**Pull request by arichnad**
Remove MtGox since they stopped trading months ago.

Also removed appcompat (if you want it).
Also added a build.xml (if you want it).

### CODE REVIEW

**Comment by toomyem** [comment]
Hi.

I'm afraid that BitcoinWidget has been bought by xbtapps and is no longer open sourced.

**Comment by arichnad** [comment]
Sounds like it's time for a hard-fork.

Any ideas on what we should call the new widget?

**Comment by gostaj** [comment]
The Android app "Bitcoin Widget" has been bought and the code for it is not open source:
https://play.google.com/store/apps/details?id=st.brothas.mtgoxwidget

The code in this Github project is released as "Crypto Currency Widget" in Google Play:
https://play.google.com/store/apps/details?id=st.brothas.ccwidget

Thanks for the pull request, feel free to fork the project if you wish.

**Comment by arichnad** [comment]
Thank you for your reply!

**Pull request closed without merging**
